### ISSUE TITLE
カテゴリ親和性ページの誤訳

### ISSUE THREAD

**Issue by notakemu** [AdobeDocs/target.ja-JP#1]
Issue in ./help/main/c-target/c-visitor-profile/category-affinity.md
![image](https://github.com/AdobeDocs/target.ja-JP/assets/15355919/fdf0d08d-48d2-4c8b-9dab-34c0ab474697)
![image](https://github.com/AdobeDocs/target.ja-JP/assets/15355919/3dda1df0-b0e8-46a2-89f9-5391fca84412)
![image](https://github.com/AdobeDocs/target.ja-JP/assets/15355919/964b2ae9-a787-4b59-9c0d-71e9c9e890ec)

**Comment by mak-adobe** [comment]
@notakemu ありがとうございます。G11N-12805のチケットで対応を開始しました。

**Comment by mak-adobe** [comment]
@notakemu 修正が完了しました。ご協力ありがとうございました。
