### ISSUE TITLE
「顧客属性」ページの翻訳がおかしい

### ISSUE THREAD

**Issue by notakemu** [AdobeDocs/target.ja-JP#3]
Issue in ./help/main/c-target/c-visitor-profile/working-with-customer-attributes.md
![image](https://github.com/AdobeDocs/target.ja-JP/assets/15355919/23b725d0-e1fd-4028-baa5-e04320d6bd9e)
![image](https://github.com/AdobeDocs/target.ja-JP/assets/15355919/2ec9328c-f526-4ee5-aed8-2798fbdd0fa9)
![image](https://github.com/AdobeDocs/target.ja-JP/assets/15355919/f9003d99-b07c-47f2-8afd-de8a6e011a32)
![image](https://github.com/AdobeDocs/target.ja-JP/assets/15355919/e49a6bbd-e89f-4436-88fd-0fd23f1f254e)
![image](https://github.com/AdobeDocs/target.ja-JP/assets/15355919/199b1dc5-1b30-4f23-8e95-a19888d59540)
![image](https://github.com/AdobeDocs/target.ja-JP/assets/15355919/60eb7d8f-64f6-4706-aaf3-dd504f27061e)
![image](https://github.com/AdobeDocs/target.ja-JP/assets/15355919/5c0ab2e8-c140-4b37-beda-f2b9f7070d46)

**Comment by mak-adobe** [comment]
@notakemu ありがとうございます。調査を開始しました。少しお待ちください。

**Comment by mak-adobe** [comment]
@notakemu お待たせしました。G11N-12956, G11N-12957, G11N-12958, G11N-12959のチケットで対応を開始しました。

**Comment by notakemu** [comment]
@mak-adobe さん、ご対応ありがとうございます！

**Comment by mak-adobe** [comment]
@notakemu 修正が完了しました。この度はご協力ありがとうございました。
