### ISSUE TITLE
翻訳エラー:  自動ターゲットの概要ページ (*3)

### ISSUE THREAD

**Issue by khagiwar** [AdobeDocs/target.ja-JP#6]
Issue in ./help/main/c-activities/auto-target/auto-target-to-optimize.md

[現在の翻訳 (a)] 注意点
    を使用する際に留意すべき重要な考慮事項がいくつかあります 自動ターゲット:
[正しい翻訳 (a)] 注意点
    自動ターゲットを使用する際には、いくつかの重要な注意点があります：
[原文 (a)] Considerations
    There are a few important considerations to keep in mind when using Auto-Target:

------------------------
[現在の翻訳 (b)] 機能 自動ターゲット ～と共通している Automated Personalization?
[正しい翻訳 (b)] 自動ターゲットと Automated Personalization の共通点とは？
[原文 (b)] What does Auto-Target have in common with Automated Personalization?

------------------------
[現在の翻訳 (c)] 方法 自動ターゲット ～とは異なる Automated Personalization?
[正しい翻訳 (c)] 自動ターゲットは Automated Personalization とどう違うのか？
[原文 (c)] How Does Auto-Target differ from Automated Personalization?

**Comment by mak-adobe** [comment]
@khagiwar ありがとうございます。G11N-12679 のチケットで対応を開始しました。

**Comment by mak-adobe** [comment]
@khagiwar 修正が完了しました。ご協力ありがとうございました。
