### ISSUE TITLE
翻訳エラー: 自動ターゲット FAQ (17 件)

### ISSUE THREAD

**Issue by khagiwar** [AdobeDocs/target.ja-JP#7]
Issue in ./help/main/c-activities/auto-target/auto-target-troubleshooting-faqs.md

自動ターゲット FAQ とトラブルシューティング
https://experienceleague.adobe.com/docs/target/using/activities/auto-target/auto-target-troubleshooting-faqs.html?lang=ja

[現在の翻訳 (a)] 次を使用するAdobeを推奨します。 自動ターゲット モデルが構築されるまで、90（コントロール）/10（ターゲット）の分割を使用しますか？
[正しい翻訳 (a)] アドビは、モデルが出来上がるまで、90（コントロール）/10（ターゲット）の分割でオートターゲットを使用することを推奨していますか？
[原文 (a)] Does Adobe you recommend using Auto Target with a 90(Control)/10(Targeted) split until the models are built?

[現在の翻訳 (b)] 回答最適なトラフィック配分の分割は、達成したい内容に応じて異なります。
[正しい翻訳 (b)] 回答 (※ web はこの部分の表示までとする。以下はクリック後に表示)
      最適なトラフィック配分の分割は、達成したい内容に応じて異なります。
[原文 (b)] Answer
   Your optimal traffic allocation split depends on what you want to accomplish.

[現在の翻訳 (c)] 訪問者が not 参照 自動ターゲット アクティビティとコンバージョンは、自分のアクティビティでコンバージョンがカウントされますか？
[正しい翻訳 (c)] 訪問者が自動ターゲット アクティビティを見ずにコンバージョンした場合、そのコンバージョンは私のアクティビティにカウントされますか？
[原文 (c)] If a visitor does not see the Auto-Target activity and converts, does the conversion count in my activity?

[現在の翻訳 (d)] +++回答いいえ。 自動ターゲット アクティビティはレポートでカウントされます。
                 +++
[正しい翻訳 (d)] 回答 (※ web はこの部分の表示までとする。以下はクリック後に表示。合わせて，現在表示されている 「+++」 を修正)
       いいえ、自動ターゲットの対象となり、自動ターゲット アクティビティを閲覧した訪問者がレポートにカウントされます。
[原文 (d)] No, only visitors who qualify for and view the Auto-Target activity are counted in reporting.

[現在の翻訳 (e)] なぜ、 自動ターゲット アクティビティは上昇率を生成しているようです。
[正しい翻訳 (e)] 私のオートターゲット活動がリフトを生み出していないように見えるのはなぜですか？
[原文 (e)] Why doesn’t my Auto-Target activity seem to be generating any lift.

[現在の翻訳 (f)] 回答： 自動ターゲット 上昇率を生成するアクティビティ：
[正しい翻訳 (f)] 回答 (※ web はこの部分の表示までとする。以下はクリック後に表示)
       自動ターゲット アクティビティがリフトを生み出すためには、4 つの要素が必要です：
[原文 (f)] Answer
        There are four factors required for an Auto-Target activity to generate lift:

[現在の翻訳 (g)]  回答：でモデルが構築されるまでに要する時間 自動ターゲット 通常、アクティビティは、選択したアクティビティの場所へのトラフィックと、アクティビティの成功指標に関連付けられたコンバージョン率に依存します。
[正しい翻訳 (g)] 回答 (※ web はこの部分の表示までとする。以下はクリック後に表示)
        通常、オートターゲットアクティビティにモデルが組み込まれるまでにかかる時間は、選択したアクティビティロケーションへのトラフィックと、アクティビティの成功指標に関連するコンバージョン率によって異なります。
[原文 (g)] Answer
        The time it takes for models to build in your Auto-Target activity typically depends on the traffic to your selected activity locations and conversion rates associated with your activity success metric.

[現在の翻訳 (h)] +++回答いいえ。パーソナライゼーションを開始するには、アクティビティ内に少なくとも 2 つのモデルが構築されている必要があります。
+++
[正しい翻訳 (h)] 回答(※ web はこの部分の表示までとする。以下はクリック後に表示。合わせて，現在表示されている 「+++」 を修正)
    パーソナライズを開始するには、アクティビティ内に少なくとも 2 つのモデルが構築されていなければなりません。
[原文 (h)] Answer
    No, there must be at least two models built within your activity for personalization to begin.

[現在の翻訳 (i)] 私はいつから私の 自動ターゲット アクティビティ？
[正しい翻訳 (i)] 自動ターゲット アクティビティの結果はいつから見ることができますか？
[原文 (i)] When can I start looking at the results of my Auto-Target activity?

[現在の翻訳 (j)] +++回答： 自動ターゲット モデルが構築されたエクスペリエンス用に、モデルが構築（緑のチェックマーク）された状態で、少なくとも 2 つのエクスペリエンスが作成された後に、テストをおこないます。
+++
[正しい翻訳 (j)] 回答 (※ web はこの部分の表示までとする。以下はクリック後に表示。合わせて，現在表示されている 「+++」 を修正)
    自動ターゲットのテスト結果を見るには、モデルが作られたエクスペリエンスを少なくとも 2 つ（緑のチェックマーク）持っている必要があります。
[原文 (j)] Answer
      You can begin looking at the results of your Auto-Target test after you have at least two experiences with models built (green checkmark) for the experience that have models built.

[現在の翻訳 (k)] 回答： Automated Personalization (AP) または 自動ターゲット (AT) アクティビティ
[正しい翻訳 (k)] 回答 (※ web はこの部分の表示までとする。以下はクリック後に表示。)
[原文 (k)]  Answer
      You can select an experience to be used as control while creating an Automated Personalization (AP) or Auto-Target (AT) activity.

[現在の翻訳 (l)] 目標指標を 自動ターゲット アクティビティ？
[正しい翻訳 (l)] 自動ターゲット アクティビチの実行中で目標指標を変更することはできますか？
[原文 (l)] Can I change the goal metric midway through an Auto-Target activity?

[現在の翻訳 (k)] 回答Adobeでは、アクティビティの途中で目標指標を変更することはお勧めしません。 Target UI を使用したアクティビティ中に目標指標を変更することは可能ですが、常に新しいアクティビティを開始する必要があります。実行後にアクティビティの目標指標を変更した場合の動作は保証されません。
[正しい翻訳 (k)] 回答 (※ web はこの部分の表示までとする。以下はクリック後に表示。)
    アドビでは、アクティビティの途中で目標指標を変更することは推奨していません。Target UIを使用してアクティビティの目標指標を変更することは可能ですが、新しいアクティビティで行うべきです。アドビは、アクティビティの実行後に目標指標を変更した場合の動作は保証していません。
[原文 (k)] Answer
Adobe does not recommend that you change the goal metric midway through an activity. Although it is possible to change the goal metric during an activity using the Target UI, you should always start a new activity. We do not warranty what happens if you change the goal metric in an activity after it is running.

[現在の翻訳 (l)] 使用できる レポートデータをリセット オプションを使用して 自動ターゲット アクティビティ？
[正しい翻訳 (l)] 自動ターゲット アクティビティの実行中にレポート データのリセットオプションを使用できますか？
[原文 (l)] Can I use the Reset Report Data option while running an Auto-Target activity?

[現在の翻訳 (m)] レポートデータをリセット オプション 自動ターゲット アクティビティは推奨されません。 目に見えるレポートデータは削除されますが、このオプションでは、自動ターゲットモデルからすべてのトレーニングレコードが削除されるわけではありません。自動ターゲットアクティビティに「レポートデータをリセット」オプションを使用する代わりに、新しいアクティビティを作成し、元のアクティビティを非アクティブにしてください。
[正しい翻訳 (m)] 回答 (※ web はこの部分の表示までとする。以下はクリック後に表示。)
    自動ターゲット アクティビティにレポートデータをリセット オプションを使用することは推奨されません。目に見えるレポートデータは削除されますが、このオプションは自動ターゲット モデルからすべてのトレーニング レコードを削除するわけではありません。自動ターゲット アクティビティでは、 レポートデータをリセット オプションを使用する代わりに、新しいアクティビティを作成し、元のアクティビティを非アクティブにしてください。
[原文 (m)] Answer
Using the Reset Report Data option for Auto-Target activities is not suggested. Although it removes the visible reporting data, this option does not remove all training records from the Auto-Target model. Instead of using the Reset Report Data option for Auto-Target activities, create a new activity and de-activate the original activity.

[現在の翻訳 (n)] 1 つのエクスペリエンスを 自動ターゲット アクティビティ？
[正しい翻訳 (n)] 自動ターゲット アクティビティから、エクスペリエンス 1 つを削除するとどうなりますか？
[原文 (n)] What happens if I remove a single experience from an Auto-Target activity?

[現在の翻訳 (o)] トラブルシューティングの提案アクティビティの設定にいくつかの変更があり、モデルの構築に要する時間を短縮できます。これには、 自動ターゲット アクティビティ、サイトへのトラフィック、選択した成功指標を示します。
[正しい翻訳 (o)] トラブルシューティングの提案 (※ web はこの部分の表示までとする。以下はクリック後に表示。)
自動ターゲットアクティビティのエクスペリエンス数、サイトへのトラフィック、選択した成功指標など、モデル構築の予想時間を短縮できるアクティビティ設定の変更がいくつかあります。
[原文 (o)] Troubleshooting suggestions
      There are several activity setup changes that can decrease the expected time to build models, including the number of experiences in your Auto-Target activity, the traffic to your site, and your selected success metric.

[現在の翻訳 (p)] トラブルシューティングの提案 AT アクティビティで上昇率を生成するには、次の 4 つの要因が必要です。
[正しい翻訳 (p)] トラブルシューティングの提案 (※ web はこの部分の表示までとする。以下はクリック後に表示。)
     AT アクティビティで上昇率を生成するには、次の 4 つの要因が必要です。
[原文 (p)] Troubleshooting suggestions
    There are four factors required for an AT activity to generate lift:

[現在の翻訳 (q)] トラブルシューティングの提案これは期待通りです。
[正しい翻訳 (q)] トラブルシューティングの提案 (※ web はこの部分の表示までとする。以下はクリック後に表示。)
    これは期待通りです。
[原文 (q)] Troubleshooting suggestions
    This is expected.

**Comment by mak-adobe** [comment]
@khagiwar ありがとうございます。調査中です。少しお待ちください。

**Comment by mak-adobe** [comment]
@khagiwar G11N-13155 のチケットで対応を開始しました。

**Comment by mak-adobe** [comment]
@khagiwar 修正が完了しました。ご協力ありがとうございました。
