### ISSUE TITLE
不適切な位置に製品名が挿入され、意味の不明な翻訳になっています

### ISSUE THREAD

**Issue by notakemu** [AdobeDocs/target.ja-JP#8]
Issue in ./help/main/c-recommendations/c-algorithms/use-adobe-analytics-with-recommendations.md

[Source] This feature is especially helpful in situations where the Target Recommendations setup is new and Analytics has much historical data to use.
[Current] この機能は、Target Recommendations 設定が新しく、使用する履歴データが多 Analytics 場合に特に便利です。
[Expected] この機能は、Target Recommendations の設定が新しく、使用する履歴データをAnalyticsが多く所有している場合に特に便利です。

[Source] Analytics data is sent via a daily feed. 
[Current] デ Analytics タは毎日のフィードで送信されます。
[Expected] Analytics データは毎日のフィードで送信されます。

**Comment by mak-adobe** [comment]
@notakemu ありがとうございます。 G11N-17190 のチケットで対応を開始しました。同じページでさらに2つの問題を見つけたので、合わせて対応しております。

**Comment by mak-adobe** [comment]
@notakemu 修正が完了しました。ご協力ありがとうございました。

**Comment by notakemu** [comment]
@mak-adobe さん、いつも迅速なご対応ありがとうございます！
